# Cargo configuration for build optimization

[build]
# Use all available CPU cores for parallel compilation
# Note: This will be capped by the actual number of cores available
jobs = 8

# Uncomment the following lines if you have mold linker installed on Linux
# mold is significantly faster than the default ld linker
# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=mold"]

# Uncomment the following lines if you have lld linker on Windows
# [target.x86_64-pc-windows-msvc]
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# Uncomment the following lines if you have zld linker on macOS
# [target.x86_64-apple-darwin]
# rustflags = ["-C", "link-arg=-fuse-ld=zld"]
